# Generated by Django 2.0.1 on 2018-01-28 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='Date of birth')),
                ('date_of_passing', models.DateTimeField(blank=True, null=True, verbose_name='Date of passing')),
                ('place_of_birth', models.TextField(verbose_name='Place of birth')),
                ('place_of_passing', models.TextField(blank=True, null=True, verbose_name='Place of passing')),
                ('is_public', models.BooleanField(default=False, help_text='Is it public?', verbose_name='Public')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bios', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(help_text='the good people that can edit this biography', related_name='editing_bios', to=settings.AUTH_USER_MODEL, verbose_name='Editors')),
                ('user', models.ForeignKey(help_text='all other personal data is stored on the user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Biography',
                'verbose_name_plural': 'Biographies',
            },
        ),
        migrations.CreateModel(
            name='ContentAtom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.DateTimeField(auto_now_add=True, verbose_name='Import date')),
                ('who', models.TextField(blank=True, help_text='who is in the atom?', verbose_name='Who')),
                ('date', models.DateTimeField(blank=True, help_text='When was this atom made?', null=True, verbose_name='Original Date')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Content Atom',
                'verbose_name_plural': 'Content Atoms',
            },
        ),
        migrations.CreateModel(
            name='Memoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_audio', models.FileField(blank=True, null=True, upload_to='', verbose_name='Story Audio')),
                ('story_text', models.TextField(blank=True, help_text='context and description of the dump', verbose_name='Story Text')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memoirs', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biography.ContentAtom', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Memoir',
                'verbose_name_plural': 'Memoirs',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_audio', models.FileField(blank=True, null=True, upload_to='', verbose_name='Story Audio')),
                ('story_text', models.TextField(blank=True, verbose_name='Story Text')),
                ('place', models.TextField(verbose_name='Place')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.Biography', verbose_name='Biography')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.AddField(
            model_name='memoir',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.Season', verbose_name='Season'),
        ),
        migrations.AddField(
            model_name='contentatom',
            name='seasons',
            field=models.ManyToManyField(related_name='memoirs', through='biography.Memoir', to='biography.Season'),
        ),
    ]
