# Generated by Django 2.0.1 on 2018-01-28 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('biography', '0001_initial'), ('biography', '0002_auto_20180128_0809'), ('biography', '0003_auto_20180128_0810'), ('biography', '0004_auto_20180128_0818')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.TextField()),
                ('place_of_birth', models.TextField()),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('place_of_death', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Is it public?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bios', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(help_text='the good people that can edit this biography', related_name='editing_bios', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='all other personal data is stored on the user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentAtom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.DateTimeField(auto_now_add=True)),
                ('who', models.TextField(default='', help_text='who is in the dump?')),
                ('date', models.DateField(blank=True, help_text='When was this dump made?', null=True)),
                ('image', models.ImageField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Memoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_audio', models.FileField(blank=True, null=True, upload_to='')),
                ('story_text', models.TextField(default='', help_text='context and description of the dump')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memoirs', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biography.ContentAtom')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_audio', models.FileField(blank=True, null=True, upload_to='')),
                ('story_text', models.TextField(blank=True)),
                ('place', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.Biography')),
            ],
        ),
        migrations.AddField(
            model_name='memoir',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.Season'),
        ),
        migrations.AddField(
            model_name='contentatom',
            name='seasons',
            field=models.ManyToManyField(related_name='memoirs', through='biography.Memoir', to='biography.Season'),
        ),
        migrations.RemoveField(
            model_name='biography',
            name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='biography',
            old_name='date_of_death',
            new_name='date_of_passing',
        ),
        migrations.AlterField(
            model_name='biography',
            name='date_of_passing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='biography',
            old_name='place_of_death',
            new_name='place_of_passing',
        ),
        migrations.AddField(
            model_name='biography',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentatom',
            name='date',
            field=models.DateTimeField(blank=True, help_text='When was this atom made?', null=True),
        ),
        migrations.AlterField(
            model_name='contentatom',
            name='who',
            field=models.TextField(blank=True, help_text='who is in the atom?'),
        ),
        migrations.AlterField(
            model_name='memoir',
            name='story_text',
            field=models.TextField(blank=True, help_text='context and description of the dump'),
        ),
    ]
