# Generated by Django 2.0.1 on 2018-02-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0002_auto_20180206_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='name',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memoir',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.Period', verbose_name='Period'),
        ),
    ]
