# Generated by Django 2.0.1 on 2018-03-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('biography', '0006_auto_20180301_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Gallery'),
        ),
    ]
