# Generated by Django 2.0.1 on 2018-01-21 09:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.DateTimeField(auto_now_add=True)),
                ('story_audio', models.FileField(upload_to='')),
                ('who', models.TextField(default='', help_text='who is in the dump?')),
                ('date', models.DateField(blank=True, help_text='When was this dump made?', null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.TextField(default='', help_text='context and description of the dump')),
                ('memory_dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tumulus.MemoryDump')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_audio', models.FileField(upload_to='')),
                ('story_text', models.TextField(default='')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tumulus',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birthday', models.DateTimeField()),
                ('birthplace', models.TextField()),
                ('deathday', models.DateTimeField(blank=True, null=True)),
                ('deathplace', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tumuli', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(related_name='edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='tumulus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tumulus.Tumulus'),
        ),
        migrations.AddField(
            model_name='personaldump',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tumulus.Season'),
        ),
        migrations.AddField(
            model_name='memorydump',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memorydump',
            name='seasons',
            field=models.ManyToManyField(related_name='dumps', through='tumulus.PersonalDump', to='tumulus.Season'),
        ),
    ]
