# Generated by Django 2.0.1 on 2018-01-25 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tumulus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tumulus',
            options={},
        ),
        migrations.AlterModelManagers(
            name='tumulus',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='tumulus',
            old_name='birthplace',
            new_name='place_of_birth',
        ),
        migrations.RenameField(
            model_name='tumulus',
            old_name='deathplace',
            new_name='place_of_death',
        ),
        migrations.RemoveField(
            model_name='tumulus',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='tumulus',
            name='deathday',
        ),
        migrations.RemoveField(
            model_name='tumulus',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='tumulus',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tumulus',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tumulus',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tumulus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
