# Generated by Django 2.0.1 on 2018-01-25 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tumulus', '0002_auto_20180125_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(default='', help_text='context and description of the dump')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memoirs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='personaldump',
            name='memory_dump',
        ),
        migrations.RemoveField(
            model_name='personaldump',
            name='season',
        ),
        migrations.AlterField(
            model_name='memorydump',
            name='seasons',
            field=models.ManyToManyField(related_name='memoirs', through='tumulus.Memoir', to='tumulus.Season'),
        ),
        migrations.DeleteModel(
            name='PersonalDump',
        ),
        migrations.AddField(
            model_name='memoir',
            name='memory_dump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tumulus.MemoryDump'),
        ),
        migrations.AddField(
            model_name='memoir',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tumulus.Season'),
        ),
    ]
